version: '3.9'
networks:
  data:
    external:
      name: waisy

services:
  trino:
    container_name: trino
    hostname: trino
    image: waisy/trino:372-graalvm-3.8.12
    ports:
      - "8080:8080"
    networks:
      - data
    volumes:
      - ./conf/:/etc/trino
    restart: always
    environment:
      TZ: Asia/Seoul